package UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javafx.scene.input.KeyCode;
/**
 *
 * @author The Vagrant Geek
 */
public class Application extends javax.swing.JFrame implements KeyListener {

    @Override
    public void keyTyped(KeyEvent ke) {
        System.out.println("keyTyped " + ke.getKeyChar());
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(ke.getKeyChar()=='1')
        {
            zone1.setMode(EspaceTravail.Mode.POINT);
        }
        else if (ke.getKeyChar()=='2')
        {
            zone1.setMode(EspaceTravail.Mode.SEGMENT);
        }
        else if (ke.getKeyChar()=='3')
        {
            zone1.setMode(EspaceTravail.Mode.VEHICULE);
        }
        else if (ke.getKeyChar()=='4')
        {
            zone1.setMode(EspaceTravail.Mode.PASSAGER);
        }
    }

    private boolean fanionClavier1 = false;
    
    public void keyPressed(KeyEvent ke) {
        if(ke.getKeyCode() == KeyEvent.VK_CONTROL)
        {
            fanionClavier1 = true;
            this.zone1.setFanionClavier1(this.fanionClavier1);
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        if(ke.getKeyCode() == KeyEvent.VK_CONTROL)
        {
            fanionClavier1 = false;
            this.zone1.setFanionClavier1(this.fanionClavier1);
        }
    }

    /**
     * Creates new form MainFrame
     */
    public Application() {
        initComponents();
        this.addKeyListener(this);
        
        
        this.BoutonNouveau.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauBarreOutils = new javax.swing.JPanel();
        BoutonNouveau = new javax.swing.JButton();
        BoutonSauvegarder = new javax.swing.JButton();
        BoutonCharger = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        BoutonRepeter = new javax.swing.JButton();
        BoutonParametres = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BoutonModePoint = new javax.swing.JButton();
        BoutonModeSegment = new javax.swing.JButton();
        BoutonModeCircuit = new javax.swing.JButton();
        BoutonModeSource = new javax.swing.JButton();
        BoutonModeProfilPassager = new javax.swing.JButton();
        PanneauEtat = new javax.swing.JPanel();
        PanneauEtatGauche = new javax.swing.JPanel();
        PanneauControleSimulation = new javax.swing.JPanel();
        BoutonDemarrerPause = new javax.swing.JButton();
        BoutonArreter = new javax.swing.JButton();
        BoutonRedemarrer = new javax.swing.JButton();
        BoutonRalentir = new javax.swing.JButton();
        BoutonAccelerer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanneauEtatDroite = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LibellePositionGeo = new javax.swing.JLabel();
        PanneauPrincipal = new javax.swing.JPanel();
        PanneauCentre = new javax.swing.JSplitPane();
        PanneauGauche = new javax.swing.JSplitPane();
        PanneauDetails = new javax.swing.JPanel();
        LibelleEnteteDetails = new javax.swing.JLabel();
        PanneauDetailsBoutons = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanneauDetailsChamps = new javax.swing.JPanel();
        zone1 = new UI.EspaceTravail();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanneauBarreOutils.setLayout(new javax.swing.BoxLayout(PanneauBarreOutils, javax.swing.BoxLayout.LINE_AXIS));

        BoutonNouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/file-2x.png"))); // NOI18N
        BoutonNouveau.setToolTipText("");
        BoutonNouveau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonNouveau.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonNouveau.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonNouveau.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonNouveau.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonNouveau.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonNouveau);

        BoutonSauvegarder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/data-transfer-download-2x.png"))); // NOI18N
        BoutonSauvegarder.setToolTipText("");
        BoutonSauvegarder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonSauvegarder.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonSauvegarder.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonSauvegarder.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonSauvegarder.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonSauvegarder.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonSauvegarder);

        BoutonCharger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/data-transfer-upload-2x.png"))); // NOI18N
        BoutonCharger.setToolTipText("");
        BoutonCharger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonCharger.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonCharger.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonCharger.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonCharger.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonCharger.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonCharger);

        BoutonAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/action-undo-2x.png"))); // NOI18N
        BoutonAnnuler.setToolTipText("");
        BoutonAnnuler.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonAnnuler.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonAnnuler.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonAnnuler.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonAnnuler.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonAnnuler.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonAnnuler);

        BoutonRepeter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/action-redo-2x.png"))); // NOI18N
        BoutonRepeter.setToolTipText("");
        BoutonRepeter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonRepeter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonRepeter.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonRepeter.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonRepeter.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonRepeter.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonRepeter);

        BoutonParametres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/wrench-2x.png"))); // NOI18N
        BoutonParametres.setToolTipText("");
        BoutonParametres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonParametres.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonParametres.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonParametres.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonParametres.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonParametres.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonParametres);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(10, 32767));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        PanneauBarreOutils.add(jSeparator1);

        BoutonModePoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/target-2x.png"))); // NOI18N
        BoutonModePoint.setToolTipText("");
        BoutonModePoint.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonModePoint.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonModePoint.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonModePoint.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonModePoint.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonModePoint.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonModePoint);

        BoutonModeSegment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/transfer-2x.png"))); // NOI18N
        BoutonModeSegment.setToolTipText("");
        BoutonModeSegment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonModeSegment.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonModeSegment.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonModeSegment.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonModeSegment.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonModeSegment.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonModeSegment);

        BoutonModeCircuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/fork-2x.png"))); // NOI18N
        BoutonModeCircuit.setToolTipText("");
        BoutonModeCircuit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonModeCircuit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonModeCircuit.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonModeCircuit.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonModeCircuit.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonModeCircuit.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonModeCircuit);

        BoutonModeSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/dashboard-2x.png"))); // NOI18N
        BoutonModeSource.setToolTipText("");
        BoutonModeSource.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonModeSource.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonModeSource.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonModeSource.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonModeSource.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonModeSource.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonModeSource);

        BoutonModeProfilPassager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/people-2x.png"))); // NOI18N
        BoutonModeProfilPassager.setToolTipText("");
        BoutonModeProfilPassager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonModeProfilPassager.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonModeProfilPassager.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonModeProfilPassager.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonModeProfilPassager.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonModeProfilPassager.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauBarreOutils.add(BoutonModeProfilPassager);

        getContentPane().add(PanneauBarreOutils, java.awt.BorderLayout.PAGE_START);

        PanneauEtat.setLayout(new java.awt.BorderLayout());

        PanneauEtatGauche.setLayout(new javax.swing.BoxLayout(PanneauEtatGauche, javax.swing.BoxLayout.LINE_AXIS));

        PanneauControleSimulation.setLayout(new javax.swing.BoxLayout(PanneauControleSimulation, javax.swing.BoxLayout.LINE_AXIS));

        BoutonDemarrerPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/media-play-2x.png"))); // NOI18N
        BoutonDemarrerPause.setToolTipText("");
        BoutonDemarrerPause.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonDemarrerPause.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonDemarrerPause.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonDemarrerPause.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonDemarrerPause.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonDemarrerPause.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauControleSimulation.add(BoutonDemarrerPause);

        BoutonArreter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/media-stop-2x.png"))); // NOI18N
        BoutonArreter.setToolTipText("");
        BoutonArreter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonArreter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonArreter.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonArreter.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonArreter.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonArreter.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauControleSimulation.add(BoutonArreter);

        BoutonRedemarrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/media-step-backward-2x.png"))); // NOI18N
        BoutonRedemarrer.setToolTipText("");
        BoutonRedemarrer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonRedemarrer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonRedemarrer.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonRedemarrer.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonRedemarrer.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonRedemarrer.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauControleSimulation.add(BoutonRedemarrer);

        BoutonRalentir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/media-skip-backward-2x.png"))); // NOI18N
        BoutonRalentir.setToolTipText("");
        BoutonRalentir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonRalentir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonRalentir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonRalentir.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonRalentir.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonRalentir.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauControleSimulation.add(BoutonRalentir);

        BoutonAccelerer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icones/media-skip-forward-2x.png"))); // NOI18N
        BoutonAccelerer.setToolTipText("");
        BoutonAccelerer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BoutonAccelerer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BoutonAccelerer.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BoutonAccelerer.setMaximumSize(new java.awt.Dimension(24, 24));
        BoutonAccelerer.setMinimumSize(new java.awt.Dimension(24, 24));
        BoutonAccelerer.setPreferredSize(new java.awt.Dimension(24, 24));
        PanneauControleSimulation.add(BoutonAccelerer);

        PanneauEtatGauche.add(PanneauControleSimulation);

        jLabel3.setText("Temps : 00:00:00 ");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 14));
        PanneauEtatGauche.add(jLabel3);
        PanneauEtatGauche.add(jSeparator2);

        jLabel6.setText("Vitesse d'exécution : 1x");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 14));
        PanneauEtatGauche.add(jLabel6);

        jLabel4.setText("Journée : 1 de X");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 14));
        PanneauEtatGauche.add(jLabel4);

        PanneauEtat.add(PanneauEtatGauche, java.awt.BorderLayout.WEST);

        jLabel5.setText("Zoom : 100%");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 14));
        jLabel5.setRequestFocusEnabled(false);
        PanneauEtatDroite.add(jLabel5);

        LibellePositionGeo.setText("Position : 46.780373, -71.277205");
        PanneauEtatDroite.add(LibellePositionGeo);

        PanneauEtat.add(PanneauEtatDroite, java.awt.BorderLayout.EAST);

        getContentPane().add(PanneauEtat, java.awt.BorderLayout.PAGE_END);

        PanneauPrincipal.setLayout(new java.awt.BorderLayout());

        PanneauCentre.setDividerLocation(150);
        PanneauCentre.setDividerSize(2);

        PanneauGauche.setDividerLocation(150);
        PanneauGauche.setDividerSize(2);
        PanneauGauche.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        PanneauCentre.setLeftComponent(PanneauGauche);

        PanneauDetails.setLayout(new java.awt.BorderLayout());

        LibelleEnteteDetails.setText("Details");
        PanneauDetails.add(LibelleEnteteDetails, java.awt.BorderLayout.NORTH);

        PanneauDetailsBoutons.setLayout(new javax.swing.BoxLayout(PanneauDetailsBoutons, javax.swing.BoxLayout.LINE_AXIS));

        jButton2.setText("Annuler");
        PanneauDetailsBoutons.add(jButton2);

        jButton1.setText("Sauvegarder");
        jButton1.setToolTipText("");
        PanneauDetailsBoutons.add(jButton1);

        PanneauDetails.add(PanneauDetailsBoutons, java.awt.BorderLayout.PAGE_END);

        PanneauDetailsChamps.setLayout(new javax.swing.BoxLayout(PanneauDetailsChamps, javax.swing.BoxLayout.PAGE_AXIS));
        PanneauDetails.add(PanneauDetailsChamps, java.awt.BorderLayout.CENTER);

        PanneauCentre.setTopComponent(PanneauDetails);
        PanneauCentre.setRightComponent(zone1);

        PanneauPrincipal.add(PanneauCentre, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanneauPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAccelerer;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonArreter;
    private javax.swing.JButton BoutonCharger;
    private javax.swing.JButton BoutonDemarrerPause;
    private javax.swing.JButton BoutonModeCircuit;
    private javax.swing.JButton BoutonModePoint;
    private javax.swing.JButton BoutonModeProfilPassager;
    private javax.swing.JButton BoutonModeSegment;
    private javax.swing.JButton BoutonModeSource;
    private javax.swing.JButton BoutonNouveau;
    private javax.swing.JButton BoutonParametres;
    private javax.swing.JButton BoutonRalentir;
    private javax.swing.JButton BoutonRedemarrer;
    private javax.swing.JButton BoutonRepeter;
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.JLabel LibelleEnteteDetails;
    private javax.swing.JLabel LibellePositionGeo;
    private javax.swing.JPanel PanneauBarreOutils;
    private javax.swing.JSplitPane PanneauCentre;
    private javax.swing.JPanel PanneauControleSimulation;
    private javax.swing.JPanel PanneauDetails;
    private javax.swing.JPanel PanneauDetailsBoutons;
    private javax.swing.JPanel PanneauDetailsChamps;
    private javax.swing.JPanel PanneauEtat;
    private javax.swing.JPanel PanneauEtatDroite;
    private javax.swing.JPanel PanneauEtatGauche;
    private javax.swing.JSplitPane PanneauGauche;
    private javax.swing.JPanel PanneauPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private UI.EspaceTravail zone1;
    // End of variables declaration//GEN-END:variables
}
