
package UI.PanneauxDetails;

import Controleur.Simulateur;
import Metier.Simulation.Simulation;
import java.util.Observable;

public class PanneauDetailsSimu extends PanneauDetails implements java.util.Observer {

    private Metier.Simulation.Simulation simuMetierLie;
    private Controleur.Simulateur simulateur;
    
    public PanneauDetailsSimu() {
        initComponents();
    }
    
    public PanneauDetailsSimu(Metier.Simulation.Simulation s)
    {
        super();
        initComponents();
        
        this.simulateur = simulateur;

        this.simuMetierLie = s;
        this.simuMetierLie.addObserver(this);
        
        rafraichir();
    }
    
    @Override
    public void rafraichir() {
       
    }

    @Override
    public void update(Observable o, Object o1) {
        this.rafraichir();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ChampDistSegmentMin = new javax.swing.JTextField();
        ChampDistSegMax = new javax.swing.JTextField();
        ChampDistSegmentMode = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ChampDistVehiculetMin = new javax.swing.JTextField();
        ChampDistVehiculeMax = new javax.swing.JTextField();
        ChampDistVehiculeMode = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ChampDistPassagerMin = new javax.swing.JTextField();
        ChampDistPassagerMax = new javax.swing.JTextField();
        ChampDistPassagerMode = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        BoutonSauvegarder = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(365, 180));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(365, 190));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setText("Nb Jours");
        jPanel1.add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel1.add(jSpinner1);

        add(jPanel1);
        add(filler2);

        jPanel3.setLayout(new java.awt.GridLayout());

        jLabel3.setText("Heure Début");
        jPanel3.add(jLabel3);

        jTextField1.setText("ChampHeureDebut");
        jPanel3.add(jTextField1);

        add(jPanel3);

        jPanel4.setAutoscrolls(true);
        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Heure Fin");
        jPanel4.add(jLabel4);

        jTextField2.setText("ChampHeureFin");
        jPanel4.add(jTextField2);

        add(jPanel4);
        add(filler1);

        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Distributions par défaut");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5);

        add(jPanel2);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel2.setText("Transit Segment");
        jLabel2.setToolTipText("");
        jPanel6.add(jLabel2);

        ChampDistSegmentMin.setText("5");
        ChampDistSegmentMin.setVerifyInputWhenFocusTarget(false);
        jPanel6.add(ChampDistSegmentMin);

        ChampDistSegMax.setText("5");
        jPanel6.add(ChampDistSegMax);

        ChampDistSegmentMode.setText("5");
        jPanel6.add(ChampDistSegmentMode);

        add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel6.setText("Gen. Véhicules");
        jLabel6.setToolTipText("");
        jPanel7.add(jLabel6);

        ChampDistVehiculetMin.setText("5");
        ChampDistVehiculetMin.setVerifyInputWhenFocusTarget(false);
        jPanel7.add(ChampDistVehiculetMin);

        ChampDistVehiculeMax.setText("5");
        jPanel7.add(ChampDistVehiculeMax);

        ChampDistVehiculeMode.setText("5");
        jPanel7.add(ChampDistVehiculeMode);

        add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel7.setText("Gen. Passagers");
        jLabel7.setToolTipText("");
        jPanel8.add(jLabel7);

        ChampDistPassagerMin.setText("5");
        ChampDistPassagerMin.setVerifyInputWhenFocusTarget(false);
        jPanel8.add(ChampDistPassagerMin);

        ChampDistPassagerMax.setText("5");
        jPanel8.add(ChampDistPassagerMax);

        ChampDistPassagerMode.setText("5");
        jPanel8.add(ChampDistPassagerMode);

        add(jPanel8);
        add(filler3);

        BoutonSauvegarder.setText("Sauvegarder");
        BoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSauvegarderActionPerformed(evt);
            }
        });
        add(BoutonSauvegarder);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSauvegarderActionPerformed

    }//GEN-LAST:event_BoutonSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.JTextField ChampDistPassagerMax;
    private javax.swing.JTextField ChampDistPassagerMin;
    private javax.swing.JTextField ChampDistPassagerMode;
    private javax.swing.JTextField ChampDistSegMax;
    private javax.swing.JTextField ChampDistSegmentMin;
    private javax.swing.JTextField ChampDistSegmentMode;
    private javax.swing.JTextField ChampDistVehiculeMax;
    private javax.swing.JTextField ChampDistVehiculeMode;
    private javax.swing.JTextField ChampDistVehiculetMin;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
