/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PanneauxDetails;

import java.util.Observable;
import javax.swing.JOptionPane;

/**
 *
 * @author The Vagrant Geek
 */
public class PanneauDetailsPoint extends PanneauDetails implements java.util.Observer {

    private Metier.Carte.Point pointMetierLie;
    private UI.Point pointUILie;
    private Controleur.Simulateur simulateur;
    
    /**
     * Creates new form PanneauDetailsPoint2
     */
    public PanneauDetailsPoint() {
        initComponents();
    }
    
    public PanneauDetailsPoint(Metier.Carte.Point p, UI.Point pUI)
    {
        super();
        initComponents();
        
        this.simulateur = simulateur;

        this.pointMetierLie = p;
        this.pointMetierLie.addObserver(this);
        
        this.pointUILie = pUI;
        
        rafraichir();
    }
    
    @Override
    public void rafraichir() {
        this.ChampLatitude.setText(String.format("%1$f", pointMetierLie.getPosition().getY()));
        this.ChampLongitude.setText(String.format("%1$f", pointMetierLie.getPosition().getX()));
        this.ChampNom.setText(pointMetierLie.getNom());
    }

    @Override
    public void update(Observable o, Object o1) {
        this.rafraichir();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ChampLatitude = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ChampLongitude = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ChampNom = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel1 = new javax.swing.JPanel();
        BoutonSauvegarder = new javax.swing.JButton();
        BoutonSupprimer = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel5 = new javax.swing.JPanel();
        LibelleSources = new javax.swing.JLabel();
        ListeSources = new javax.swing.JComboBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Latitude");
        jPanel2.add(jLabel2, java.awt.BorderLayout.NORTH);

        ChampLatitude.setText("ChampLatitude");
        jPanel2.add(ChampLatitude, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Longitude");
        jPanel3.add(jLabel3, java.awt.BorderLayout.NORTH);

        ChampLongitude.setText("ChampLongitude");
        jPanel3.add(ChampLongitude, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Nom");
        jPanel4.add(jLabel4, java.awt.BorderLayout.NORTH);

        ChampNom.setText("ChampNom");
        jPanel4.add(ChampNom, java.awt.BorderLayout.CENTER);

        add(jPanel4);
        add(filler1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        BoutonSauvegarder.setText("Sauvegarder");
        BoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSauvegarderActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonSauvegarder);

        BoutonSupprimer.setText("Supprimer");
        BoutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(BoutonSupprimer);

        add(jPanel1);
        add(filler2);

        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        LibelleSources.setText("Sources");
        jPanel5.add(LibelleSources, java.awt.BorderLayout.NORTH);

        ListeSources.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(ListeSources, java.awt.BorderLayout.CENTER);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSauvegarderActionPerformed
        
        this.obtenirApplication().getSimulateur().modifierPoint(this.pointMetierLie, Double.parseDouble(this.ChampLongitude.getText()), Double.parseDouble(this.ChampLatitude.getText()), this.ChampNom.getText());
        this.obtenirApplication().repaint();
    }//GEN-LAST:event_BoutonSauvegarderActionPerformed

    private void BoutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSupprimerActionPerformed
        if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this.obtenirApplication(), "Désirez-vous vraiment retirer ce point?", "Retirer ce point?", JOptionPane.YES_NO_OPTION))
        {
            this.obtenirApplication().getSimulateur().retirerPoint(this.pointMetierLie);
            this.obtenirApplication().repaint();
        }         
    }//GEN-LAST:event_BoutonSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.JButton BoutonSupprimer;
    private javax.swing.JTextField ChampLatitude;
    private javax.swing.JTextField ChampLongitude;
    private javax.swing.JTextField ChampNom;
    private javax.swing.JLabel LibelleSources;
    private javax.swing.JComboBox ListeSources;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
