package UI.PanneauxDetails;

import Controleur.Simulateur;
import java.util.Observable;


public class PanneauDetailsCircuit extends PanneauDetails implements java.util.Observer {

    private Metier.Circuit.Circuit circuitMetierLie;
    private Controleur.Simulateur simulateur;
    
    /**
     * Creates new form PanneauDetailsPoint2
     */
    public PanneauDetailsCircuit(Simulateur sim) {
        super();
        initComponents();
        this.simulateur = sim;
    }
    
    public PanneauDetailsCircuit(Metier.Circuit.Circuit cMetier, Simulateur sim)
    {
        this(sim);
        
        this.circuitMetierLie = cMetier;
        
        rafraichir();
    }
    
    @Override
    public void rafraichir() {
        this.ChampNom.setText(circuitMetierLie != null ? circuitMetierLie.getNom() : "");
    }

    @Override
    public void update(Observable o, Object o1) {
        this.rafraichir();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(5, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ChampNom = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        BoutonSauvegarder = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(filler2, java.awt.BorderLayout.WEST);
        jPanel4.add(filler3, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Nom");
        jPanel1.add(jLabel4);

        ChampNom.setText("ChampNom");
        jPanel1.add(ChampNom);

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel4);
        add(filler1);

        BoutonSauvegarder.setText("Sauvegarder");
        BoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSauvegarderActionPerformed(evt);
            }
        });
        add(BoutonSauvegarder);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSauvegarderActionPerformed
        this.simulateur.sauvergarderNouveauCircuit(this.ChampNom.getText());
        this.obtenirApplication().revalidate();
        this.obtenirApplication().repaint();
    }//GEN-LAST:event_BoutonSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.JTextField ChampNom;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
