/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PanneauxDetails;

import Controleur.Simulateur;
import Metier.Simulation.Simulation;
import java.util.Observable;

public class PanneauDetailsSimu extends PanneauDetails implements java.util.Observer {

    private Metier.Simulation.Simulation simuMetierLie;
    private Controleur.Simulateur simulateur;
    
    public PanneauDetailsSimu() {
        initComponents();
    }
    
    public PanneauDetailsSimu(Metier.Simulation.Simulation s)
    {
        super();
        initComponents();
        
        this.simulateur = simulateur;

        this.simuMetierLie = s;
        this.simuMetierLie.addObserver(this);
        
        rafraichir();
    }
    
    @Override
    public void rafraichir() {
       
    }

    @Override
    public void update(Observable o, Object o1) {
        this.rafraichir();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        BoutonSauvegarder = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(filler1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nb Jours");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        jTextField1.setText("ChampNbJours");
        jPanel1.add(jTextField1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Heure Départ - Fin");
        jPanel4.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("00:00");
        jPanel5.add(jTextField2);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("00:00");
        jPanel5.add(jTextField3);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel4);

        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jLabel3.setText("Distributions par défaut");
        jPanel2.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Véhicules");
        jPanel3.add(jLabel4);

        jTextField4.setText("5");
        jPanel3.add(jTextField4);

        jTextField5.setText("5");
        jPanel3.add(jTextField5);

        jTextField6.setText("5");
        jPanel3.add(jTextField6);

        jPanel2.add(jPanel3);

        jLabel5.setText("Segments");
        jPanel6.add(jLabel5);

        jTextField7.setText("5");
        jPanel6.add(jTextField7);

        jTextField8.setText("5");
        jPanel6.add(jTextField8);

        jTextField9.setText("5");
        jPanel6.add(jTextField9);

        jPanel2.add(jPanel6);

        jLabel6.setText("Passagers");
        jPanel7.add(jLabel6);

        jTextField10.setText("5");
        jPanel7.add(jTextField10);

        jTextField11.setText("5");
        jPanel7.add(jTextField11);

        jTextField12.setText("5");
        jPanel7.add(jTextField12);

        jPanel2.add(jPanel7);

        add(jPanel2);

        BoutonSauvegarder.setText("Sauvegarder");
        BoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSauvegarderActionPerformed(evt);
            }
        });
        add(BoutonSauvegarder);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSauvegarderActionPerformed
        
        this.obtenirApplication().revalidate();
    }//GEN-LAST:event_BoutonSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
