package UI.PanneauxDetails;

import Controleur.Simulateur;
import java.util.Observable;
import javax.swing.JOptionPane;
import Metier.Exceptions.CreationInvalideException;

public class PanneauDetailsCircuit extends PanneauDetails implements java.util.Observer {

    private Metier.Circuit.Circuit circuitMetierLie;
    
    public PanneauDetailsCircuit() {
        super();
        initComponents();
        this.LibelleEntete.setText("Création d'un nouveau circuit");
    }
    
    public PanneauDetailsCircuit(Metier.Circuit.Circuit cMetier)
    {
        this.circuitMetierLie = cMetier;
        this.LibelleEntete.setText("Détails : Circuit \"" + this.circuitMetierLie.getNom() + "\"");
        rafraichir();
    }
    
    @Override
    public void rafraichir() {
        this.ChampNom.setText(circuitMetierLie != null ? circuitMetierLie.getNom() : "");
    }

    @Override
    public void update(Observable o, Object o1) {
        this.rafraichir();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        LibelleEntete = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ChampNom = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        BoutonSauvegarder = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 15));
        jPanel5.setLayout(new java.awt.BorderLayout());

        LibelleEntete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LibelleEntete.setText("Nom");
        jPanel5.add(LibelleEntete, java.awt.BorderLayout.NORTH);

        add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Nom");
        jPanel4.add(jLabel4, java.awt.BorderLayout.NORTH);
        jPanel4.add(ChampNom, java.awt.BorderLayout.CENTER);

        add(jPanel4);
        add(filler1);

        BoutonSauvegarder.setText("Sauvegarder");
        BoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSauvegarderActionPerformed(evt);
            }
        });
        add(BoutonSauvegarder);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSauvegarderActionPerformed
        try
        {
            this.obtenirApplication().getSimulateur().sauvergarderCircuit(this.ChampNom.getText());
            this.obtenirApplication().viderPanneauDetails();
        }
        catch(CreationInvalideException ex)
        {
            JOptionPane.showMessageDialog(this.obtenirApplication(), "Le circuit ne peut pas être sauvegardé : " + ex.getMessage(), "Création invalide d'un circuit.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BoutonSauvegarderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSauvegarder;
    private javax.swing.JTextField ChampNom;
    private javax.swing.JLabel LibelleEntete;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
