package UI.PanneauxDetails;

import java.util.Observable;

public class PanneauDistribution extends PanneauDetails {

    private Metier.Distribution distributionCourante;
    
    /**
     * Creates new form PanneauDetailsPoint2
     */
    public PanneauDistribution() {
        initComponents();
    }
    
    public PanneauDistribution(Metier.Distribution dt)
    {
        super();
        initComponents();
        setDistribution(dt);
    }

    public void setDistribution(Metier.Distribution dt)
    {
        this.distributionCourante  = dt;
        rafraichir();
    }
    
    @Override
    public void rafraichir()
    {
        this.ChampMaximum.setText(((Double)distributionCourante.getMax()).toString());
        this.ChampMinimum.setText(((Double)distributionCourante.getMin()).toString());
        this.ChampMode.setText(((Double)distributionCourante.getMode()).toString());
        this.revalidate();
    }
    
    public double obtenirMin(){
        return Double.parseDouble(this.ChampMinimum.getText());
    }
    
    public double obtenirMax(){
        return Double.parseDouble(this.ChampMaximum.getText());
    }
    
    public double obtenirMode(){
        return Double.parseDouble(this.ChampMode.getText());
    }
    
    public String validerValeurs()
    {
        
        
        
        String retour = "";
        double min = 0;
        double max = 0;
        double mode = 0;
        boolean nombresValides = true;
        try{
            min = Double.parseDouble(this.ChampMinimum.getText());   
        }
        catch(NumberFormatException ex){
            nombresValides = false;
            retour += "La valeur minimale est obligatoire et doit être un nombre.\r\n";
        }
        
        try{
            max = Double.parseDouble(this.ChampMaximum.getText());   
        }
        catch(NumberFormatException ex){
            nombresValides = false;
            retour += "La valeur maximale est obligatoire et doit être un nombre.\r\n";
        }
        
        try{
            mode = Double.parseDouble(this.ChampMode.getText());   
        }
        catch(NumberFormatException ex){
            nombresValides = false;
            retour += "Le mode est obligatoire et doit être un nombre.\r\n";
        }
        
        if(nombresValides)
        {
            if(min > mode || min > max)
            {
                retour += "La valeur minimale doit être plus petite que le mode et la valeur maximale.\r\n";
            }
            if(mode < min  || max < mode)
            {
                retour += "Le mode doit être en la valeur minimale et la valeur maximale.\r\n";
            }
            if(max < mode || max < min)
            {
                retour += "La valeur maximale doit être plus grande que la valeur minimale et le mode.\r\n";
            }
        }
        
        return retour;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5));
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ChampMinimum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ChampMode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ChampMaximum = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(filler1);

        jRadioButton1.setText("Paramètres par défaut");
        add(jRadioButton1);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Paramètres spécifiques");
        add(jRadioButton2);

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Minimum");
        jPanel2.add(jLabel2, java.awt.BorderLayout.NORTH);
        jPanel2.add(ChampMinimum, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Mode");
        jLabel4.setToolTipText("");
        jPanel4.add(jLabel4, java.awt.BorderLayout.NORTH);
        jPanel4.add(ChampMode, java.awt.BorderLayout.CENTER);

        add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Maximum");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, java.awt.BorderLayout.NORTH);
        jPanel3.add(ChampMaximum, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChampMaximum;
    private javax.swing.JTextField ChampMinimum;
    private javax.swing.JTextField ChampMode;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
